create or replace TABLE TEAM_ART_DW.FOLLOWMEE.DEVICE_DATA_WITH_CLOSEST_PLANT (
    AS_OF_DATE        DATE,   
	DEVICE_ID         VARCHAR(16777216),
	TRACKER_DATE      TIMESTAMP_NTZ(9),
	TRACKER_LATITUDE  FLOAT,
	TRACKER_LONGITUDE FLOAT,
    SPEED_MPH         NUMBER(38,0),
    DIRECTION         NUMBER(38,0),
    ACCURACY          NUMBER(38,0),
    GROUP_NAME        VARCHAR(16777216),
	PLANT_ID NUMBER(38,0),
	DEVICE_CLOSEST_PLANT_DISTANCE_MS DECIMAL(18,2) 
);