create or replace table TEAM_ART_DW.FOLLOWMEE.DEVICE_DATA_AGG
(	AS_OF_DATE DATE,
	DEVICE_ID VARCHAR(16777216),
	TRACKER_DATE_BEGIN TIMESTAMP_NTZ(9),
	TRACKER_DATE_END TIMESTAMP_NTZ(9),
	TRACKER_LAT_BEGIN FLOAT,
	TRACKER_LAT_END FLOAT,
	TRACKER_LONG_BEGIN FLOAT,
	TRACKER_LONG_END FLOAT,
	TRACKER_PLANT_ID_BEGIN NUMBER(38,0),
	TRACKER_PLANT_ID_END NUMBER(38,0),
	TRACKER_PLANT_DISTANCE_MS_BEGIN NUMBER(18,2),
	TRACKER_PLANT_DISTANCE_MS_END NUMBER(18,2),
    TRACKER_SPEED_MPH_BEGIN NUMBER(38,0),
    TRACKER_SPEED_MPH_END   NUMBER(38,0),
    TRACKER_DIRECTION_BEGIN NUMBER(38,0),
    TRACKER_DIRECTION_END   NUMBER(38,0),
    TRACKER_ACCURACY        NUMBER(38,0),
    GROUP_NAME              VARCHAR(16777216), 
	TRACKER_SPENT_TIME_MIN NUMBER(18,0),
	TRACKER_TRAVELLED_DISTANCE_MS NUMBER(18,2) 

);
