create or replace function TEAM_ART_DW.FOLLOWMEE.FN_DEVICE_DATA_ANALYTICS(P_DATE date)
returns table (
	AS_OF_DATE DATE,
	TRACKER_HOUR_PERIOD VARCHAR(16777216),
	TRACKER_DATE_HOUR NUMBER(2,0),
	GROUP_NAME VARCHAR(16777216),
	DEVICE_ID VARCHAR(16777216),
	DEVICE_NAME VARCHAR(16777216),
	TRACKER_DATE_BEGIN TIMESTAMP_NTZ(9),
	TRACKER_DATE_END TIMESTAMP_NTZ(9),
	TRACKER_LAT_BEGIN FLOAT,
	TRACKER_LAT_END FLOAT,
	TRACKER_LONG_BEGIN FLOAT,
	TRACKER_LONG_END FLOAT,
	TRACKER_PLANT_ID_BEGIN NUMBER(38,0),
	TRACKER_PLANT_NAME_BEGIN VARCHAR(34),
	TRACKER_PLANT_ID_END NUMBER(38,0),
	TRACKER_PLANT_NAME_END VARCHAR(34),
	TRACKER_PLANT_DISTANCE_MS_BEGIN NUMBER(18,2),
	TRACKER_PLANT_DISTANCE_MS_END NUMBER(18,2),
	TRACKER_SPEED_MPH_BEGIN NUMBER(38,0),
	TRACKER_SPEED_MPH_END NUMBER(38,0),
	TRACKER_DIRECTION_BEGIN NUMBER(38,0),
	TRACKER_DIRECTION_END NUMBER(38,0),
	TRACKER_ACCURACY NUMBER(38,0),
	TRACKER_SPENT_TIME_MIN NUMBER(18,0),
	TRACKER_TRAVELLED_DISTANCE_MS NUMBER(18,2),
	TRACKER_POSITION_STATUS VARCHAR(9),
	TRACKER_SPEED_STATUS VARCHAR(16777216),
	TRACKER_DIRECTION_STATUS VARCHAR(16777216),
	TRACKER_PLANT_DISTANCE_MS_ABS VARCHAR(16777216)
)
AS
$$
WITH CTE_Devices AS(
  SELECT CAST( DATE AS DATE) AS AS_OF_DATE, DEVICE_ID, MAX(UPPER(DEVICE_NAME)) AS DEVICE_NAME 
  FROM SLATECO_DW.FOLLOWMEE.DEVICE_DATA
  GROUP BY 1,2
),
CTE_Plants AS (
  SELECT PLANT_ID, PLANT_NAME, GROUP_NAME AS PLANT_GROUP_NAME FROM TEAM_ART_DW.FOLLOWMEE.TRANSPORTATION_PLANTS
)
SELECT DA.AS_OF_DATE,
       CASE WHEN DATE_PART( 'hour', DA.TRACKER_DATE_END ) BETWEEN  0 AND  4  THEN '1.MIDNIGHT'
            WHEN DATE_PART( 'hour', DA.TRACKER_DATE_END ) BETWEEN  5 AND  7  THEN '2.EARLY MORNING'
            WHEN DATE_PART( 'hour', DA.TRACKER_DATE_END ) BETWEEN  8 AND 11  THEN '3.MORNING'
            WHEN DATE_PART( 'hour', DA.TRACKER_DATE_END ) BETWEEN 12 AND 14  THEN '4.MIDDDAY'
            WHEN DATE_PART( 'hour', DA.TRACKER_DATE_END ) BETWEEN 15 AND 18  THEN '5.AFTERNOON'
            WHEN DATE_PART( 'hour', DA.TRACKER_DATE_END ) > 18 THEN               '6.EVENING/NIGHT'
       END AS TRACKER_HOUR_PERIOD, 
       DATE_PART( 'hour', DA.TRACKER_DATE_END ) AS TRACKER_DATE_HOUR,
       DA.GROUP_NAME,
       DA.DEVICE_ID,
       EV.DEVICE_NAME, 
       DA.TRACKER_DATE_BEGIN,
       DA.TRACKER_DATE_END,
       DA.TRACKER_LAT_BEGIN,
       DA.TRACKER_LAT_END,
       DA.TRACKER_LONG_BEGIN,
       DA.TRACKER_LONG_END,
       DA.TRACKER_PLANT_ID_BEGIN,
       PL1.PLANT_NAME AS TRACKER_PLANT_NAME_BEGIN,
       DA.TRACKER_PLANT_ID_END,
       PL2.PLANT_NAME AS TRACKER_PLANT_NAME_END,
       DA.TRACKER_PLANT_DISTANCE_MS_BEGIN,
       DA.TRACKER_PLANT_DISTANCE_MS_END,
       DA.TRACKER_SPEED_MPH_BEGIN,
       DA.TRACKER_SPEED_MPH_END,
       DA.TRACKER_DIRECTION_BEGIN,
       DA.TRACKER_DIRECTION_END,
       DA.TRACKER_ACCURACY,
       DA.TRACKER_SPENT_TIME_MIN,
       DA.TRACKER_TRAVELLED_DISTANCE_MS,
       CASE WHEN (( DA.TRACKER_PLANT_DISTANCE_MS_BEGIN = DA.TRACKER_PLANT_DISTANCE_MS_END )
                 OR 
                 (  DA.TRACKER_TRAVELLED_DISTANCE_MS = 0 ) 
                 OR
                 (  DA.TRACKER_LAT_BEGIN = DA.TRACKER_LAT_END)
                 OR 
                 (  DA.TRACKER_SPEED_MPH_END = 0 ) 
                 ) THEN '0.STOPPED'
                 ELSE '1.MOVING' END AS TRACKER_POSITION_STATUS,
        CASE WHEN DA.TRACKER_SPEED_MPH_END = 0               THEN '1.NO SPEED'
             WHEN DA.TRACKER_SPEED_MPH_END BETWEEN 1 AND  10 THEN '2.VERY SLOW'
             WHEN DA.TRACKER_SPEED_MPH_END BETWEEN 11 AND 20 THEN '3.SLOW'
             WHEN DA.TRACKER_SPEED_MPH_END BETWEEN 21 AND 50 THEN '4.MEAN'
             WHEN DA.TRACKER_SPEED_MPH_END > 50              THEN '5.FAST'
        END AS TRACKER_SPEED_STATUS, 
        CASE WHEN DA.TRACKER_DIRECTION_BEGIN = DA.TRACKER_DIRECTION_END THEN '1.NO DIRECTION'
             WHEN DA.TRACKER_DIRECTION_BEGIN < DA.TRACKER_DIRECTION_END THEN '2.GOING UP'
             WHEN DA.TRACKER_DIRECTION_BEGIN > DA.TRACKER_DIRECTION_END THEN '3.GOING DOWN'
        END AS TRACKER_DIRECTION_STATUS,
        CASE WHEN (CAST( DA.TRACKER_PLANT_DISTANCE_MS_END AS INTEGER) - 1) BETWEEN 0 AND 1 THEN '1.IN PLANT'
             WHEN (CAST( DA.TRACKER_PLANT_DISTANCE_MS_END AS INTEGER) - 1) BETWEEN 2 AND 4 THEN '2.CLOSE TO PLANT'
             WHEN (CAST( DA.TRACKER_PLANT_DISTANCE_MS_END AS INTEGER) - 1) BETWEEN 5 AND 6 THEN '3.ARRIVING/LEAVING PLANT'
             WHEN (CAST( DA.TRACKER_PLANT_DISTANCE_MS_END AS INTEGER) - 1) > 6             THEN '4.IN ROUTE'
        END AS TRACKER_PLANT_DISTANCE_MS_ABS          
FROM FOLLOWMEE.DEVICE_DATA_AGG AS DA  
JOIN CTE_Devices AS EV   ON EV.AS_OF_DATE = DA.AS_OF_DATE AND EV.DEVICE_ID = DA.DEVICE_ID 
JOIN CTE_Plants  AS PL1  ON PL1.PLANT_ID = DA.TRACKER_PLANT_ID_BEGIN
JOIN CTE_Plants  AS PL2  ON PL2.PLANT_ID = DA.TRACKER_PLANT_ID_END
WHERE DA.AS_OF_DATE = P_DATE
ORDER BY DA.AS_OF_DATE, DA.DEVICE_ID, DA.TRACKER_DATE_BEGIN
$$
